import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Citycard from '../components/Citycard'
import Flight from '../components/Flight'


export default function Home() {
  return (
    <div>
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
      <div className="header-wraper">
        <div className=" container">
            <div className="row">
                <div className="col-sm-12 col-md-12">
                    <p className="flights">Flights Price Finder</p>
                </div>
            </div>
        </div>
    </div>
    {/* <!--====== Header end ======-->
        <!--====== Body Start ======--> */}
    <div className="body-wraper">

                    <div className="images-wrap">
                        <Image width="373px"
      height="145px" src="/images/1.png" alt="Nature" className="responsive"/> 
      <Flight />
                    </div>
                    <h2 className="are">We are about to change everything you know about finding a flight</h2>
                    <p className="trip">Customize to your trip and your desires</p>
                    <button><a href="#">Check our deals</a></button>
                    <div className="check-wraper">
            <p className="check">Check the popular destinations</p> 
            <Citycard imgUrl={"/images/2.png"} cityName={"Los Angeles (US)"} link={"#"} />
            <Citycard imgUrl={"/images/3.png"} cityName={"Las vegas (US)"} link={"#"} />
            <Citycard imgUrl={"/images/4.png"} cityName={"Miami (US)"} link={"#"} />
            <Citycard imgUrl={"/images/5.png"} cityName={"Orlando (US)"} link={"#"} />      
    </div>
            
    </div>
    
    {/* <!--====== Body end ======-->

      <!--====== check Start ======-->
    
    <!--====== check end ======--> */}

        {/* <h1 classNameName={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 classNameName="text-3xl font-bold underline">
      Hello world!
    </h1>

        <p classNameName={styles.description}>
          Get started by editing{' '}
          <code classNameName={styles.code}>pages/index.js</code>
        </p>

        <div classNameName={styles.grid}>
          <a href="https://nextjs.org/docs" classNameName={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" classNameName={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            classNameName={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            classNameName={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer classNameName={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span classNameName={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
